name: clairvoyancemedium_app
description: Application mobile officielle ClairVoyanceMedium.com
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.14.1
  webview_flutter_android: ^4.14.1
  url_launcher: ^6.3.2
  onesignal_flutter: ^5.6.10
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
